twilio: # Twilio gateway configuration
  accountId: AC0956b7e235142286114b5a6c627fe5fA
  accountToken: 9d36cdf69dd60c855d117c8e57854f55
  numbers:
    - "+12056560069"
  messagingServicesId: 
  localDomain: 127.0.0.1

push:
  queueSize: 20

#redphone:
#  authKey: # Deprecated

turn: # TURN server configuration
  secret: test
  uris:
    - turn:127.0.0.1:3478

cache: # Redis server configuration for cache cluster
  url: redis://127.0.0.1:6379
  replicaUrls:
    - redis://127.0.0.1:6379

directory:
  redis: # Redis server configuration for directory cluster
    url: redis://127.0.0.1:6379
    replicaUrls:
      - redis://127.0.0.1:6379
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    userAuthenticationTokenUserIdSecret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  sqs:
    accessKey: AAAAAAAAAAAAAAAAAAAA
    accessSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    queueUrl: https://sqs.ap-southeast-1.amazonaws.com/111111111111/konglomerat-queue
  server:
    replicationUrl: http://127.0.0.1:8080
    replicationPassword: mypassword
    replicationCaCertificate: MIIGDzCCA/egAwIBAgIUUmP5XBG9pEmYwiUblNg99VS6msAwDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNVBAYTAlNHMRIwEAYDVQQIDAlTaW5nYXBvcmUxEjAQBgNVBAcMX/XgYucvAxW+btWOVNT0C8ZOBxujxeqCE4cSeRYq/uq9iopMqc6rZDjI61o6l5f2n9l4ST32vI9VjA5BdB/YQ+e2QEruRdBH3+l0n+jWr+8yT8FE4iW0Ey6j4dT2QefFLTZidTSgjz/RaWNgQ7ucclaoew==
#    reconciliationChunkSize:       # CDS reconciliation chunk size
#    reconciliationChunkIntervalMs: # CDS reconciliation chunk interval, in milliseconds

messageCache:
  redis:
    url: redis://127.0.0.1:6379
    replicaUrls:
      - redis://127.0.0.1:6379

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: postgres
  password: 123456
  url: jdbc:postgresql://192.168.2.160:5432/accountdb

attachments: # AWS S3 configuration
  endpoint: http://192.168.2.160:9000
  accessKey: 3UR9EMG74SKJ7WNBK0O2
  accessSecret: OL6+YfD2pUWncnjD8AMhnNRf9prIWI+pAjf0KKGC
  bucket: attachments
  region: us-east-1

profiles: # AWS S3 configuration
  endpoint: http://192.168.2.160:9000
  accessKey: 3UR9EMG74SKJ7WNBK0O2
  accessSecret: OL6+YfD2pUWncnjD8AMhnNRf9prIWI+pAjf0KKGC
  bucket: profiles
  region: us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: postgres
  password: 123456
  url: jdbc:postgresql://192.168.2.160:5432/accountdb

abuseDatabase:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 123456
  url: jdbc:postgresql://192.168.2.160:5432/accountdb

apn: # Apple Push Notifications configuration
  pushCertificate:
    "-----BEGIN CERTIFICATE-----\n
    MIIGADCCBOigAwIBAgIIMXfOpMDCQ5owDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV\n
    BAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js\n
    ZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3\n
    aWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw\n
    HhcNMTkwODMwMDcyNTEyWhcNMjAwOTI4MDcyNTEyWjCBhzEdMBsGCgmSJomT8ixk\n
    AQEMDWNvbS5iam0uaW1hcHAxKzApBgNVBAMMIkFwcGxlIFB1c2ggU2VydmljZXM6\n
    IGNvbS5iam0uaW1hcHAxEzARBgNVBAsMClc3WTQyNzRGUzgxFzAVBgNVBAoMDkJs\n
    YWlyIEJlbmphbWluMQswCQYDVQQGEwJQSDCCASIwDQYJKoZIhvcNAQEBBQADggEP\n
    ADCCAQoCggEBANlFsXFi0kNsobdqDEr3pfpJ64cczcOzsgOYToJerakrJOTGyWos\n
    QTAq15HEn2+jK6u56cR5YDCu8m/LZMlrn8k3jJSZqfgKuCFWv/HDA/iJ0tv9l686\n
    9YRDKLkqh0hJt3NsrjNeNqQ6A6owXwlNYPNzqua7p6THf1bMHD+9uJ1HtIhsDF/L\n
    r2x4yLxuWb4tb9K+ovb6BccOCflOhA1B/Eq2eXtkmtHWxecWznq8lIET0/9MUEHS\n
    A8/4JToOrqAWU0nNUgj2qCEN0hiSkzftX0fPbmpAj4roldNGUHRHzyZRDcvgidaC\n
    lzVZOQQzWSg9hEdgmG8HYs011ljLlgbj/lMCAwEAAaOCAl0wggJZMAwGA1UdEwEB\n
    /wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEcBgNVHSAE\n
    ggETMIIBDzCCAQsGCSqGSIb3Y2QFATCB/TCBwwYIKwYBBQUHAgIwgbYMgbNSZWxp\n
    YW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFj\n
    Y2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBh\n
    bmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2Vy\n
    dGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA1BggrBgEFBQcCARYpaHR0\n
    cDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkwEwYDVR0lBAww\n
    CgYIKwYBBQUHAwIwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL2NybC5hcHBsZS5j\n
    b20vd3dkcmNhLmNybDAdBgNVHQ4EFgQUShXc2zPFliw/UI7nPfG46gdwIuIwDgYD\n
    VR0PAQH/BAQDAgeAMBAGCiqGSIb3Y2QGAwEEAgUAMBAGCiqGSIb3Y2QGAwIEAgUA\n
    MG4GCiqGSIb3Y2QGAwYEYDBeDA1jb20uYmptLmltYXBwMAUMA2FwcAwSY29tLmJq\n
    bS5pbWFwcC52b2lwMAYMBHZvaXAMGmNvbS5iam0uaW1hcHAuY29tcGxpY2F0aW9u\n
    MA4MDGNvbXBsaWNhdGlvbjANBgkqhkiG9w0BAQsFAAOCAQEAADxsJEu/nly1KWOV\n
    ZiTXGIUgdhAcSc2Xfl3lq2RXNXpHm7U5lBBh232CJW8WfjHO+4tDGfWv7Ennrhc7\n
    24YyYNoZjwgTRCiX3NIIsbZOVwZlknIMFPihVR7O+5dFSRBhwezljT47gVDNI3F3\n
    E4pcn0nCQo3YRNFBh1ImcN7dZ8xL3QxtfxsMXgCf5bXBVfI68fbIcZE++QckHh7F\n
    twf+j02+/PTK5A8YGHz2UD+qtac65Ad9/segRhnbrnBjlbsHBfEnijFHkLnjOINV\n
    IS6DehdMYT2wS0nQj37fqeDkECANVYdcocnl/vihfq40zFRuVznPif/ONIKNL5Th\n
    bisJ0A==\n
    -----END CERTIFICATE-----"
#    "-----BEGIN CERTIFICATE-----\nMIIGADCCBOigAwIBAgIIMXfOpMDCQ5owDQYJKoZIhvcNAQELBQAwgZYxCzAJBgNV\nBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSwwKgYDVQQLDCNBcHBsZSBXb3Js\nZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9uczFEMEIGA1UEAww7QXBwbGUgV29ybGR3\naWRlIERldmVsb3BlciBSZWxhdGlvbnMgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw\nHhcNMTkwODMwMDcyNTEyWhcNMjAwOTI4MDcyNTEyWjCBhzEdMBsGCgmSJomT8ixk\nAQEMDWNvbS5iam0uaW1hcHAxKzApBgNVBAMMIkFwcGxlIFB1c2ggU2VydmljZXM6\nIGNvbS5iam0uaW1hcHAxEzARBgNVBAsMClc3WTQyNzRGUzgxFzAVBgNVBAoMDkJs\nYWlyIEJlbmphbWluMQswCQYDVQQGEwJQSDCCASIwDQYJKoZIhvcNAQEBBQADggEP\nADCCAQoCggEBANlFsXFi0kNsobdqDEr3pfpJ64cczcOzsgOYToJerakrJOTGyWos\nQTAq15HEn2+jK6u56cR5YDCu8m/LZMlrn8k3jJSZqfgKuCFWv/HDA/iJ0tv9l686\n9YRDKLkqh0hJt3NsrjNeNqQ6A6owXwlNYPNzqua7p6THf1bMHD+9uJ1HtIhsDF/L\nr2x4yLxuWb4tb9K+ovb6BccOCflOhA1B/Eq2eXtkmtHWxecWznq8lIET0/9MUEHS\nA8/4JToOrqAWU0nNUgj2qCEN0hiSkzftX0fPbmpAj4roldNGUHRHzyZRDcvgidaC\nlzVZOQQzWSg9hEdgmG8HYs011ljLlgbj/lMCAwEAAaOCAl0wggJZMAwGA1UdEwEB\n/wQCMAAwHwYDVR0jBBgwFoAUiCcXCam2GGCL7Ou69kdZxVJUo7cwggEcBgNVHSAE\nggETMIIBDzCCAQsGCSqGSIb3Y2QFATCB/TCBwwYIKwYBBQUHAgIwgbYMgbNSZWxp\nYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVzIGFj\nY2VwdGFuY2Ugb2YgdGhlIHRoZW4gYXBwbGljYWJsZSBzdGFuZGFyZCB0ZXJtcyBh\nbmQgY29uZGl0aW9ucyBvZiB1c2UsIGNlcnRpZmljYXRlIHBvbGljeSBhbmQgY2Vy\ndGlmaWNhdGlvbiBwcmFjdGljZSBzdGF0ZW1lbnRzLjA1BggrBgEFBQcCARYpaHR0\ncDovL3d3dy5hcHBsZS5jb20vY2VydGlmaWNhdGVhdXRob3JpdHkwEwYDVR0lBAww\nCgYIKwYBBQUHAwIwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL2NybC5hcHBsZS5j\nb20vd3dkcmNhLmNybDAdBgNVHQ4EFgQUShXc2zPFliw/UI7nPfG46gdwIuIwDgYD\nVR0PAQH/BAQDAgeAMBAGCiqGSIb3Y2QGAwEEAgUAMBAGCiqGSIb3Y2QGAwIEAgUA\nMG4GCiqGSIb3Y2QGAwYEYDBeDA1jb20uYmptLmltYXBwMAUMA2FwcAwSY29tLmJq\nbS5pbWFwcC52b2lwMAYMBHZvaXAMGmNvbS5iam0uaW1hcHAuY29tcGxpY2F0aW9u\nMA4MDGNvbXBsaWNhdGlvbjANBgkqhkiG9w0BAQsFAAOCAQEAADxsJEu/nly1KWOV\nZiTXGIUgdhAcSc2Xfl3lq2RXNXpHm7U5lBBh232CJW8WfjHO+4tDGfWv7Ennrhc7\n24YyYNoZjwgTRCiX3NIIsbZOVwZlknIMFPihVR7O+5dFSRBhwezljT47gVDNI3F3\nE4pcn0nCQo3YRNFBh1ImcN7dZ8xL3QxtfxsMXgCf5bXBVfI68fbIcZE++QckHh7F\ntwf+j02+/PTK5A8YGHz2UD+qtac65Ad9/segRhnbrnBjlbsHBfEnijFHkLnjOINV\nIS6DehdMYT2wS0nQj37fqeDkECANVYdcocnl/vihfq40zFRuVznPif/ONIKNL5Th\nbisJ0A==\n-----END CERTIFICATE-----"
  pushKey:
    "-----BEGIN PRIVATE KEY-----\n
    MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDZRbFxYtJDbKG3\n
    agxK96X6SeuHHM3Ds7IDmE6CXq2pKyTkxslqLEEwKteRxJ9voyuruenEeWAwrvJv\n
    y2TJa5/JN4yUman4CrghVr/xwwP4idLb/ZevOvWEQyi5KodISbdzbK4zXjakOgOq\n
    MF8JTWDzc6rmu6ekx39WzBw/vbidR7SIbAxfy69seMi8blm+LW/SvqL2+gXHDgn5\n
    ToQNQfxKtnl7ZJrR1sXnFs56vJSBE9P/TFBB0gPP+CU6Dq6gFlNJzVII9qghDdIY\n
    kpM37V9Hz25qQI+K6JXTRlB0R88mUQ3L4InWgpc1WTkEM1koPYRHYJhvB2LNNdZY\n
    y5YG4/5TAgMBAAECggEBAMFRyXhhvURQu/M+YIGzp/LzIqWtc0fV82ZPdkt5gnsq\n
    8EC+vyfBCJ+a/wOsN1BVlt3NJbqzZGrsvrnJ93tgT2PyERuHPjx9DShcz5yFMFtM\n
    BlnHYdeAVkPAndNji8s+DASfhsAd6/Bjzi73qxfTyZfUKxPxlFCBUUQhiGEOpd0J\n
    86TnaKO/WfFSmwtzBa4eMkFDAqU6Nj6N8c1yE8oCtcQ4tFWIFZxSLy+IgJes1gPr\n
    KS0Z6LZB1AjlG5Z7k9xT0T9/ZRwCtORj3JajaQ/vQTcv3/AYtJlK+dMHbXFeZ225\n
    jK+nzSkEV5qDNj7hgw9bfq2ypiiW7c7VREy9ndpFe4ECgYEA+iPYkyLjblilD8WT\n
    9NNeV3Tagkr7XMpDU9yhWartyGV0gg3eubKyJOzaAHnGiCLMZYuKYSiz3RLpkSPZ\n
    J0s9LpzYxsRPKiF9TrBDE27ROgPkQmZtkW6yMbg6v7eEMDjSDQ2gR/XkLI70TfFy\n
    CAPQUm3xev3Y/sNxlFXqcWHPEBkCgYEA3ly7B/Uefeef1DoefVtSKqraqa3ws6A6\n
    gFOE4DmPPifaxwDNg2X732F18lqIMtuoRiGzTEZF1BX6txZIcuQlHxyjdqwNchia\n
    TtHZtAgUzNYf0qGNOIsgtRq5PRwaFhOZOl9DU64tiJ0THf14/lJ6IMZtcobvJOZQ\n
    zM1hkh5pX0sCgYEA7ZU0dHQTvlA13ugTottL5RdZH53mZ3i5QCLzob5HASrT4V8Z\n
    KBnBOG86lG8VkWIz71L9SVEmnRkEfVWmQLsmzmotP4Vfh62tXhruaru7wDXIDQVK\n
    lnKkj7LjIgtFY6PkZn+FuDOl2GijRJDKdTBiIpjIXsBS5Y9vBqwf9DcpO6kCgYEA\n
    2fYrnvE2olOY537QxC/vqsMu84P8nRZCQeecJ+5D6rlGSisPR+1/psbxxk3Xk4Kc\n
    v6HpDqsTZ4Dj8PN2sKfRe12nHXwo8d4L45bvvvjs6pw5NU4GD5bQyLUZPj19lIZB\n
    fGZEqJHjMDZHtu3u29wcumPGhKyfXZwlN5taONB2mWECgYEA6ZiRfCc/Y9XK/hcF\n
    J18tTxbqcN2pqAOZ/iF3z6Xgdg1TR1w26JZB0FP7UUSP39iq/iYL4yvSjiMRrIFt\n
    /X02XYv3qR1Gtm8A+TZlWBgrvxORHb6mxrfu016d3ulDptVDc/X78PNSrs60gbfb\n
    1a0RIg2Tq05YfsNurG9eyYHMskg=\n
    -----END PRIVATE KEY-----"
#    "-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQDANZ4+nDd0aoWjMjZe7v0doa/kiZHw83qkFG0ozF6T6RLOhAYo\neMh1RjthsXnU5YuzgL5seHKECRI2Ch2CEI7aAxztwWBEbdiMshjM1AeKnzsp6CPI\npJKTzWDzJ47Yo34loJo5dNp6OuPi8siGpMhdeGgqBImKzSC0bIMCEekbAQIDAQAB\nAoGAW92Em5IYYxjCdIR8PhVlfrMXmVgzG4GTfTaSEazUC0ebiH7LXq6TyJFfskqb\n2yg3A/0lhjxvJzIatR9SiSaWz0IUdvj7AF8KDPKgOiAzIyI8/1c5FmvqEaznFlOO\nBE1aOwnN+EgwpXFKYPQUNLp9bHVxx4HYrALFzryqB6Kfi20CQQDipY9pyQgkmZ8Z\n18pFeT7ovlVGEnvksxbZFx7jT2LtElae9YIlX1iiHL4svGi3x/0vEYGdZ/pEgC02\ntD0DU/k/AkEA2RpLhkQ2U+ZbwHitfV/ONvsjXnt4AjmOkS1vQrNNxMCGmjLoWLu5\niBtMT3ceQVQK57o+vx6CU1dYAf5NCmebvwJAJBLT27N6j1DAKP3WnO4qXCMHMYr5\nmzIB/fWXHfjhtvgHP2+2Ejq1wb+vaTFnvXCgVKCFr8b/5207RQy09VWlQwJBAJmH\neOVok6rdewEv1jCVcfV7wFVupz2binCsWsQmnNaI+CdP3PPzPY89Dsgbiu/UCSo6\nkWkCoFNjrz8poT28a20CQFIip0aHpXJzc/IjvUsA9o8OSqwRypdSQOro0jgtfSk1\nECYd0mWD/uaI/263NqvL3MKxhSFdILpIHhstIp2tGTI=\n-----END RSA PRIVATE KEY-----"
  bundleId: com.bjm.imapp
  sandbox: true

gcm: # GCM Configuration
  senderId: 383199917875 #90077701463
  apiKey: AAAAWTh-tzM:APA91bH6NngHODtb9AdSn-FEiGfLtSfMD2URXkpw2WO6l-B80xvAUdaI2NzkjK3qdjLJIhcQ3P1L3SxyBx37ZgsknoWnvCO8lavXbK5bT8xDDvuosFMJqgRF9e8gs-gFOwb2vizv4z2M #AIzaSyAHNIwGE0yKG9QnDZQMcziNAF-0zliXOtH

recaptcha:
  secret: abcd

accountDatabaseCrawler:
  chunkSize: 1000
  chunkIntervalMs: 1000000

unidentifiedDelivery:
  certificate: CiUIDBIhBbTz4h1My+tt+vw+TVscgUe/DeHS0W02tPWAWbTO2xc3EkD+go4bJnU0AcnFfbOLKoiBfCzouZtDYMOVi69rE7r4U9cXREEqOkUmU2WJBjykAxWPCcSTmVTYHDw7hkSp/puG
  privateKey: ABOxG29xrfq4E7IrW11Eg7+HBbtba9iiS0500YoBjn4=
  expiresDays: 100

voiceVerification:
  url: https://server.konglomerat.net
  locales:
    - en

pushScheduler:
  url: redis://127.0.0.1:6379/pushScheduler
  replicaUrls:
    - redis://127.0.0.1:6379/pushSchedulerReplica
  circuitBreaker:
    failureRateThreshold: 50
    ringBufferSizeInHalfOpenState: 10
    ringBufferSizeInClosedState: 100
    waitDurationInOpenStateInSeconds: 10

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081





